set(CPACK_PACKAGE_VENDOR "Ultimaker")
set(CPACK_PACKAGE_CONTACT "Ultimaker <software-embedded@ultimaker.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "VNC server for Ultimaker 3D printers")
set(CPACK_PACKAGE_VERSION_MAJOR 9999)
set(CPACK_PACKAGE_VERSION_MINOR 99)
set(CPACK_PACKAGE_VERSION_PATCH 99)
set(CPACK_PACKAGE_PRIORITY optional)
set(CPACK_PACKAGE_SECTION "utils")
set(CPACK_GENERATOR "DEB")

find_package(Git)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD OUTPUT_VARIABLE GIT_VERSION_BRANCH WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND ${GIT_EXECUTABLE} describe --tags --dirty OUTPUT_VARIABLE GIT_VERSION_TAGS_DIRTY WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(GIT_VERSION "${GIT_VERSION_TAGS_DIRTY}-${GIT_VERSION_BRANCH}")
else()
    set(GIT_VERSION "Unknown")
    message(WARNING "Git not found, not adding git revision description")
endif()

if("${CPACK_PACKAGE_VERSION}" STREQUAL "9999.99.99")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "(${GIT_VERSION}) ${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
endif()

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE all)

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/debian/postinst")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libvncserver1, libc6 (>= 2.28)")

# Customize the output .deb file name to include architecture
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")

include(CPack)
